apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pollen-frontend
  name: pollen-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-pollen-frontend
  template:
    metadata:
      labels:
        name: pod-pollen-frontend
      name: pollen-frontend
    spec:
      containers:
      - image: ertis/pollen-web-frontend:v1.0
        name: pollen-frontend
        ports:
        - containerPort: 8520
        imagePullPolicy: Always
        env:
          - name: BACKEND_PROXY_URL
            value: http://pollen-backend:8540

---

apiVersion: v1
kind: Service
metadata:
  name: pollen-frontend
spec:
  selector:
    name: pod-pollen-frontend
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 8520
    targetPort: 8520