apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pollen-yolo-executor
  name: pollen-yolo-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-pollen-yolo-executor
  template:
    metadata:
      labels:
        name: pod-pollen-yolo-executor
      name: pollen-yolo-executor
    spec:
      containers:
      - image: ertis/pollen-web-yoloexecutor:v1.0
        name: pollen-yolo-executor
        ports:
        - containerPort: 8530
        imagePullPolicy: Always
        # env:
        # - name: BACKEND_URL
        #   value: http://backend:8540

---

apiVersion: v1
kind: Service
metadata:
  name: pollen-yolo-executor
spec:
  selector:
    name: pod-pollen-yolo-executor
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 8530
    targetPort: 8530

